{% set version = "3.9.0" %}

package:
  name: flit-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: d75edf5eb324da20d53570a6a6f87f51e606eee8384925cd66a90611140844c7
  folder: source

build:
  script: python -m pip install --no-deps -vv source/flit_core/
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
  run_constrained:
    - flit {{ version }}

test:
  imports:
    - flit_core
    - flit_core.common

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - takluyver
    - beckermr
