{% set version = "3.9.0" %}

package:
  name: flit-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: d75edf5eb324da20d53570a6a6f87f51e606eee8384925cd66a90611140844c7
  folder: source

# flit_core strict has set its confiugraton to use specifically this script.
build:
  script: python -m pip install --no-deps -vv source/flit_core/
  number: 0
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python


test:
  imports:
    - flit_core
    - flit_core.common
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules
  description: |
    Flit is a simple way to put Python packages and modules on PyPI. It only
    requires a single file to be added to your package, and no configuration in
    setup.py.
  doc_source_url: https://flit.readthedocs.io/
  dev_url: https://flit.readthedocs.io/

